// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlygfgdwyqbhxwazibwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRseWdmZ2R3eXFiaHh3YXppYnd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MTgyMTMsImV4cCI6MjA2NzI5NDIxM30.sY3ZBtSQyCE8ewuFq_smbXbNrT6j8-KgGMTU6Fm86gI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});